In [19]:
import torch
import torch.nn as nn
import numpy as np

In [6]:
l = np.load(r'wifi_track_data\dacang\train_data\rewards_deep_irl_fc_epoch94_0115.npy')

In [8]:
n = np.array([1,2,3,4,5,6,7,8,9,10])
n = n*n
n

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
import time
from tqdm import tqdm

with tqdm(total=2.1) as pbar:
    pbar.set_description('Processing')
    # 手动设置：每次更新10个进度，一共更新20次，总共更新total：200
    for i in range(20):
         # 进行动作, 这里是过0.1s
         time.sleep(0.1)
         # 进行进度更新, 这里设置10个
         pbar.update(0.1)


Processing:  95%|█████████▌| 2.0000000000000004/2.1 [00:02<00:00,  1.09s/it] 


In [13]:
delta = np.inf
delta = 0.4
thre = 0.01
type(delta-thre)

float

In [3]:
l = np.array([-1,1,1,2,-2])
l.__abs__()

array([1, 1, 1, 2, 2])

In [3]:
np.load(r'wifi_track_data\dacang\train_data\rewards_deep_irl_fc_epoch731_0111.npy')[-1]

array([ 0.8862939 ,  0.99071676,  0.89625823,  0.9965055 ,  0.9994608 ,
        0.99801046,  0.9996555 ,  0.9997961 ,  0.9992751 ,  0.9997638 ,
        0.999875  ,  0.9998925 ,  0.9998398 ,  0.9999213 ,  0.99994034,
        0.99991477,  0.9998857 ,  0.9998216 ,  0.9996682 ,  0.9998786 ,
        0.99994683,  0.9999605 ,  0.9999542 ,  0.99994695,  0.9999361 ,
        0.9999147 ,  0.9998628 ,  0.9997463 ,  0.9995196 ,  0.9999198 ,
        0.99995947,  0.9999658 ,  0.9999642 ,  0.999963  ,  0.9999596 ,
        0.99988455,  0.9998088 ,  0.9996796 ,  0.9994317 ,  0.99890697,
        0.99992895,  0.99996215,  0.9999691 ,  0.9999679 ,  0.9999673 ,
        0.9997812 ,  0.999591  ,  0.99914443,  0.9997962 ,  0.9999286 ,
        0.99996144,  0.9999698 ,  0.9999729 ,  0.99982285,  0.9996588 ,
        0.99926007,  0.9982251 ,  0.9999487 ,  0.9999685 ,  0.9999753 ,
        0.99997705,  0.9996964 ,  0.9993139 ,  0.9981888 ,  0.9952026 ,
        0.99915457,  0.9999581 ,  0.9999717 ,  0.999976  ,  0.99

In [20]:
p = np.array([[0,1],[0.5,0.5],[1,0]])

In [30]:
new_p = p[:,:,np.newaxis]
new_p

array([[[0. ],
        [1. ]],

       [[0.5],
        [0.5]],

       [[1. ],
        [0. ]]])

In [54]:
d = np.array([[[1,0,1],[0,100,0]],
              [[1,0,2],[0, 0, 1]],
              [[0,10,0],[0, 3, 1]]])
d_swapped = np.transpose(d, (2, 1, 0))
d_swapped

array([[[  1,   1,   0],
        [  0,   0,   0]],

       [[  0,   0,  10],
        [100,   0,   3]],

       [[  1,   2,   0],
        [  0,   1,   1]]])

In [55]:
result = p[:,:,np.newaxis]*d_swapped
result

array([[[ 0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ]],

       [[ 0. ,  0. ,  5. ],
        [50. ,  0. ,  1.5]],

       [[ 1. ,  2. ,  0. ],
        [ 0. ,  0. ,  0. ]]])

In [56]:
x = result.sum(1)
x = torch.from_numpy(x)
x

tensor([[ 0.0000,  0.0000,  0.0000],
        [50.0000,  0.0000,  6.5000],
        [ 1.0000,  2.0000,  0.0000]], dtype=torch.float64)

In [57]:
initial = np.array([0.3,0.7,0])

In [58]:
initial = torch.from_numpy(initial)

In [13]:
initial.shape

torch.Size([3])

In [63]:
mu = initial.repeat(2,1)

In [60]:
mu_np 

tensor([[0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000]], dtype=torch.float64)

In [64]:
for i in range(1,2):
    mu[i,:] = mu[i-1,:]@x
mu

tensor([[ 0.3000,  0.7000,  0.0000],
        [35.0000,  0.0000,  4.5500]], dtype=torch.float64)

tensor([[ 0.3000,  0.7000,  0.0000],
        [35.0000,  0.0000,  4.5500]], dtype=torch.float64)

In [65]:
mu.sum(0)

tensor([1.3000, 2.7000, 1.0000], dtype=torch.float64)

In [67]:
c = (1,2)
c[0]

1

In [69]:
reward_mat = np.array([[ 0, 0, 1, 1, 1, 0, 1, 0, 0, 2],
                   [ 0, 0, 1, 2, 1, 0, 0, 0, 1, 1],
                   [ 0,-1, 0, 1, 0, 0, 0, 0, 0, 1],
                   [-1,-1,-1, 0, 0, 0, 0, 0, 0, 0],
                   [ 0,-1, 0, 0, 0, 1, 0, 0, 0, 0],
                   [ 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 1, 1, 1, 2, 1, 1, 0, 0],
                   [ 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 0, 0, 0, 1, 0, 0, 0,-1],
                   [ 0, 0, 0, 0, 0, 0, 0, 0,-1,-2],])

In [71]:
reward_mat.reshape(100).shape

(100,)

In [2]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[go.Scatter(x=[0, 1], y=[0, 1])],
    layout=go.Layout(
        xaxis=dict(range=[0, 5], autorange=False),
        yaxis=dict(range=[0, 5], autorange=False),
        title="Start Title",
        updatemenus=[dict(
            type="buttons",
            buttons=[dict(label="Play",
                          method="animate",
                          args=[None])])]
    ),
    frames=[go.Frame(data=[go.Scatter(x=[1, 2], y=[1, 2])]),
            go.Frame(data=[go.Scatter(x=[1, 4], y=[1, 4])]),
            go.Frame(data=[go.Scatter(x=[3, 4], y=[3, 4])],
                     layout=go.Layout(title_text="End Title"))]
)

fig.show()