In [3]:
import torch
import torch.nn as nn
import numpy as np

In [4]:
p = np.array([[0,1],[0.5,0.5],[1,0]])

In [5]:
p[:,:,np.newaxis].shape

(3, 2, 1)

In [6]:
d = np.array([[[1,0,0],[0,1,0]],
              [[1,0,0],[0, 0, 1]],
              [[0,1,0],[0, 0, 1]]])

In [27]:
d_swapped = np.transpose(d, (2, 1, 0))
d_swapped


array([[[1, 1, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 1, 1]]])

In [8]:
result = p[:,:,np.newaxis]*d

In [9]:
result.shape

(3, 2, 3)

In [10]:
x = result.sum(1)
x = torch.from_numpy(x)
x

tensor([[0.0000, 1.0000, 0.0000],
        [0.5000, 0.0000, 0.5000],
        [0.0000, 1.0000, 0.0000]], dtype=torch.float64)

In [11]:
initial = np.array([0.3,0.7,0])

In [12]:
initial = torch.from_numpy(initial)

In [13]:
initial.shape

torch.Size([3])

In [14]:
mu = initial.repeat(5,1)

In [15]:
mu

tensor([[0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000]], dtype=torch.float64)

In [24]:
p = np.array([[0,1],[0.5,0.5],[1,0]])
p = p[:,:,np.newaxis]
p.shape

(3, 2, 1)

In [26]:
d

array([[[1, 0, 0],
        [0, 1, 0]],

       [[1, 0, 0],
        [0, 0, 1]],

       [[0, 1, 0],
        [0, 0, 1]]])

In [28]:
p*d_swapped

array([[[0. , 0. , 0. ],
        [0. , 0. , 0. ]],

       [[0. , 0. , 0.5],
        [0.5, 0. , 0. ]],

       [[0. , 0. , 0. ],
        [0. , 0. , 0. ]]])

In [63]:
for i in range(1,5):
    mu[i,:] = torch.matmul(mu[i-1,:],x)

In [6]:
mu

tensor([[0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000]], dtype=torch.float64)

In [65]:
mu.sum(0)

tensor([1.3000, 2.7000, 1.0000], dtype=torch.float64)

In [67]:
c = (1,2)
c[0]

1

In [69]:
reward_mat = np.array([[ 0, 0, 1, 1, 1, 0, 1, 0, 0, 2],
                   [ 0, 0, 1, 2, 1, 0, 0, 0, 1, 1],
                   [ 0,-1, 0, 1, 0, 0, 0, 0, 0, 1],
                   [-1,-1,-1, 0, 0, 0, 0, 0, 0, 0],
                   [ 0,-1, 0, 0, 0, 1, 0, 0, 0, 0],
                   [ 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 1, 1, 1, 2, 1, 1, 0, 0],
                   [ 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 0, 0, 0, 1, 0, 0, 0,-1],
                   [ 0, 0, 0, 0, 0, 0, 0, 0,-1,-2],])

In [71]:
reward_mat.reshape(100).shape

(100,)