In [1]:
1//3

0

In [2]:
import torch
import torch.nn as nn
import numpy as np

In [6]:
d = {1:[2],3:[4]}
list(d.values())

[[2], [4]]

In [6]:
l = np.load(r'wifi_track_data\dacang\train_data\rewards_deep_irl_fc_epoch94_0115.npy')

In [3]:
n = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
n.shape

(2, 2, 5)

In [4]:
n.reshape(n.shape[0],-1)

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [14]:
import time
from tqdm import tqdm

with tqdm(total=2.1) as pbar:
    pbar.set_description('Processing')
    # 手动设置：每次更新10个进度，一共更新20次，总共更新total：200
    for i in range(20):
         # 进行动作, 这里是过0.1s
         time.sleep(0.1)
         # 进行进度更新, 这里设置10个
         pbar.update(0.1)


Processing:  95%|█████████▌| 2.0000000000000004/2.1 [00:02<00:00,  1.09s/it] 


In [13]:
delta = np.inf
delta = 0.4
thre = 0.01
type(delta-thre)

float

In [3]:
l = np.array([-1,1,1,2,-2])
l.__abs__()

array([1, 1, 1, 2, 2])

In [4]:
np.load(r'wifi_track_data\dacang\train_data\rewards_deep_irl_fc_epoch10000_0122.npy')[-1]

array([3.06134491e-04, 6.98709488e-03, 2.05003773e-04, 5.84280849e-01,
       1.64828286e-01, 2.49455553e-02, 9.31214333e-01, 1.82469726e-01,
       1.14941179e-06, 1.87841295e-06, 6.21517120e-06, 3.36545929e-02,
       9.11137998e-01, 1.58931971e-01, 4.83539443e-05, 4.28070877e-07,
       3.00293237e-07, 5.77240962e-06, 9.24921042e-05, 8.03018265e-05,
       6.75234560e-06, 1.51504818e-02, 9.00563836e-01, 7.20365345e-01,
       2.82101333e-03, 2.71354802e-04, 4.04667575e-04, 3.55769735e-05,
       5.11673152e-01, 9.09208655e-01, 4.18880075e-01, 1.92401145e-04,
       6.73088187e-04, 1.24309488e-04, 3.37590754e-01, 8.98752034e-01,
       1.05692144e-03, 2.33176932e-01, 7.19539583e-01, 4.54376757e-01,
       1.41463075e-02, 2.52352445e-04, 1.27090991e-03, 1.09135429e-03,
       4.91683713e-05, 4.62389949e-07, 7.72917628e-01, 3.66144180e-01,
       2.52536323e-04, 8.74981657e-02, 8.20681810e-01, 7.41231143e-01,
       3.01656965e-02, 1.63271825e-03, 1.38260238e-03, 5.91513162e-05,
      

In [20]:
p = np.array([[0,1],[0.5,0.5],[1,0]])

In [30]:
new_p = p[:,:,np.newaxis]
new_p

array([[[0. ],
        [1. ]],

       [[0.5],
        [0.5]],

       [[1. ],
        [0. ]]])

In [54]:
d = np.array([[[1,0,1],[0,100,0]],
              [[1,0,2],[0, 0, 1]],
              [[0,10,0],[0, 3, 1]]])
d_swapped = np.transpose(d, (2, 1, 0))
d_swapped

array([[[  1,   1,   0],
        [  0,   0,   0]],

       [[  0,   0,  10],
        [100,   0,   3]],

       [[  1,   2,   0],
        [  0,   1,   1]]])

In [55]:
result = p[:,:,np.newaxis]*d_swapped
result

array([[[ 0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ]],

       [[ 0. ,  0. ,  5. ],
        [50. ,  0. ,  1.5]],

       [[ 1. ,  2. ,  0. ],
        [ 0. ,  0. ,  0. ]]])

In [56]:
x = result.sum(1)
x = torch.from_numpy(x)
x

tensor([[ 0.0000,  0.0000,  0.0000],
        [50.0000,  0.0000,  6.5000],
        [ 1.0000,  2.0000,  0.0000]], dtype=torch.float64)

In [57]:
initial = np.array([0.3,0.7,0])

In [58]:
initial = torch.from_numpy(initial)

In [13]:
initial.shape

torch.Size([3])

In [63]:
mu = initial.repeat(2,1)

In [60]:
mu_np 

tensor([[0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000]], dtype=torch.float64)

In [64]:
for i in range(1,2):
    mu[i,:] = mu[i-1,:]@x
mu

tensor([[ 0.3000,  0.7000,  0.0000],
        [35.0000,  0.0000,  4.5500]], dtype=torch.float64)

tensor([[ 0.3000,  0.7000,  0.0000],
        [35.0000,  0.0000,  4.5500]], dtype=torch.float64)

In [65]:
mu.sum(0)

tensor([1.3000, 2.7000, 1.0000], dtype=torch.float64)

In [67]:
c = (1,2)
c[0]

1

In [69]:
reward_mat = np.array([[ 0, 0, 1, 1, 1, 0, 1, 0, 0, 2],
                   [ 0, 0, 1, 2, 1, 0, 0, 0, 1, 1],
                   [ 0,-1, 0, 1, 0, 0, 0, 0, 0, 1],
                   [-1,-1,-1, 0, 0, 0, 0, 0, 0, 0],
                   [ 0,-1, 0, 0, 0, 1, 0, 0, 0, 0],
                   [ 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 1, 1, 1, 2, 1, 1, 0, 0],
                   [ 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 0, 0, 0, 1, 0, 0, 0,-1],
                   [ 0, 0, 0, 0, 0, 0, 0, 0,-1,-2],])

In [71]:
reward_mat.reshape(100).shape

(100,)

In [2]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[go.Scatter(x=[0, 1], y=[0, 1])],
    layout=go.Layout(
        xaxis=dict(range=[0, 5], autorange=False),
        yaxis=dict(range=[0, 5], autorange=False),
        title="Start Title",
        updatemenus=[dict(
            type="buttons",
            buttons=[dict(label="Play",
                          method="animate",
                          args=[None])])]
    ),
    frames=[go.Frame(data=[go.Scatter(x=[1, 2], y=[1, 2])]),
            go.Frame(data=[go.Scatter(x=[1, 4], y=[1, 4])]),
            go.Frame(data=[go.Scatter(x=[3, 4], y=[3, 4])],
                     layout=go.Layout(title_text="End Title"))]
)

fig.show()