In [1]:
import torch
import torch.nn as nn
import numpy as np

In [52]:
p = np.array([[0,1],[0.5,0.5],[1,0]])

In [53]:
p[:,:,np.newaxis].shape

(3, 2, 1)

In [54]:
d = np.array([[[1,0,0],[0,1,0]],
              [[1,0,0],[0, 0, 1]],
              [[0,1,0],[0, 0, 1]]])

In [55]:
d.shape

(3, 2, 3)

In [56]:
result = p[:,:,np.newaxis]*d

In [57]:
result.shape

(3, 2, 3)

In [58]:
x = result.sum(1)
x = torch.from_numpy(x)
x

tensor([[0.0000, 1.0000, 0.0000],
        [0.5000, 0.0000, 0.5000],
        [0.0000, 1.0000, 0.0000]], dtype=torch.float64)

In [2]:
initial = np.array([0.3,0.7,0])

In [3]:
initial = torch.from_numpy(initial)

In [4]:
initial.shape

torch.Size([3])

In [5]:
mu = initial.repeat(5,1)

In [63]:
for i in range(1,5):
    mu[i,:] = torch.matmul(mu[i-1,:],x)

In [6]:
mu

tensor([[0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000],
        [0.3000, 0.7000, 0.0000]], dtype=torch.float64)

In [65]:
mu.sum(0)

tensor([1.3000, 2.7000, 1.0000], dtype=torch.float64)

In [67]:
c = (1,2)
c[0]

1

In [69]:
reward_mat = np.array([[ 0, 0, 1, 1, 1, 0, 1, 0, 0, 2],
                   [ 0, 0, 1, 2, 1, 0, 0, 0, 1, 1],
                   [ 0,-1, 0, 1, 0, 0, 0, 0, 0, 1],
                   [-1,-1,-1, 0, 0, 0, 0, 0, 0, 0],
                   [ 0,-1, 0, 0, 0, 1, 0, 0, 0, 0],
                   [ 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 1, 1, 1, 2, 1, 1, 0, 0],
                   [ 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                   [ 0, 0, 0, 0, 0, 1, 0, 0, 0,-1],
                   [ 0, 0, 0, 0, 0, 0, 0, 0,-1,-2],])

In [71]:
reward_mat.reshape(100).shape

(100,)