In [1]:
import gymnasium as gym

In [2]:
a = gym.spaces.MultiDiscrete([30,2])

In [3]:
a.sample()

array([29,  1], dtype=int64)

In [4]:
import numpy as np
a = gym.spaces.Box(low=0.,high=1.0,shape=(10,),dtype=np.float32)

In [5]:
a.sample()

array([0.66455036, 0.3582289 , 0.05827048, 0.08836222, 0.1711679 ,
       0.38253942, 0.823996  , 0.58002937, 0.14867319, 0.2568312 ],
      dtype=float32)

In [14]:
t = np.array([[1,2,3,4,5],[6,7,8,9,10]])
t2 = t.reshape(-1)
t2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
t2.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])